#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f composer.json ]; then
    docker run \
        --rm \
        --volume "$(pwd)":/app \
        --entrypoint /usr/local/bin/entrypoint-suexec.sh \
        --workdir /app \
        dreadlabs/php-lib:7.0-dev \
        composer install --prefer-dist --optimize-autoloader --no-interaction
        composer global require hirak/prestissimo
else
    echo "==> No composer.json found in root directory. Please initialize the project."
fi
